services:
  - type: worker
    name: feedback-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: CHANNEL_ID
        value: your_channel_id_here
